spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:32768/postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true